### PR TITLE
feat(clangformat): use binary instead of npm

### PR DESCRIPTION
**Pull request by Edholm**
much faster and removes the middle-man.

### CODE REVIEW

**Comment by Edholm** [comment]
I _think_ this was the last NPM tool that we hadn't switched out yet

**Review by viktorvoltaire — COMMENTED** [review]
Oh, I thought NPM was the only solution for this one, have you tried it?

**Review by odsod — APPROVED** [review]
Nice one!

**Comment by Edholm** [comment]
```
❯ ls -l .mage/tools/clang-format/v1.6.0/clang-format
-rwxr-xr-x 1 edholm users 4433472 22 jan 12.08 .mage/tools/clang-format/v1.6.0/clang-format

~/go/src/github.com/einride/vehicle-logger ci/mage-tools*
❯ .mage/tools/clang-format/v1.6.0/clang-format --version
clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7af584ed87cc6eddb6adbc451c90fb8867469e06)
```

**Comment by viktorvoltaire** [comment]
Sweet! 🧙‍♀️

**Pull request merged**
