### PR TITLE
feat(mggit): add DefaultBranch

### PR DESCRIPTION
**Pull request by odsod**

### CODE REVIEW

**Review by Edholm — APPROVED** [review]
LGTM!

**Review by viktorvoltaire — APPROVED** [review]
👍

**Comment by odsod** [comment]
@viktorvoltaire @Edholm This was harder than it looked, due to how the repo is cloned on GitHub actions, the symbolic ref trick isn't usable. Tried a few different variants but came up short. Closing this for now, until we come up with a working approach!

**Comment by viktorvoltaire** [comment]
> @viktorvoltaire @Edholm This was harder than it looked, due to how the repo is cloned on GitHub actions, the symbolic ref trick isn't usable. Tried a few different variants but came up short. Closing this for now, until we come up with a working approach!

Yeah retrieving things with git can certainly be tricky, I think this one is so minor anyway. Not a problem for the consumer just to change it to what ever default branch they have 🧙‍♀️

Thanks for trying!

**Pull request closed without merging**
