### PR TITLE
feat: adds command to generate .mage

### PR DESCRIPTION
**Pull request by viktorvoltaire**
With this, one can run `go run go.einride.tech/mage-tools` to get everything needed to get started with mage-tools

### CODE REVIEW

**Review by Edholm — APPROVED** [review]
damn nice! This will ease the transition immensely!

**Review by odsod — APPROVED** [review]
Very nice!

Some thoughts:

* Most tools use `init` as a subcommand for this type of action - worth using the same convention here?
* Do we want an `example` directory and simply `go:embed` the files from there, instead of having inline string constants?

**Comment by viktorvoltaire** [comment]
> * Most tools use `init` as a subcommand for this type of action - worth using the same convention here?
> * Do we want an `example` directory and simply `go:embed` the files from there, instead of having inline string constants?
Yes on both +1

**Comment by viktorvoltaire** [comment]
WDYT @odsod ?

**Review by odsod — APPROVED** [review]
Nice!

**Pull request merged**
