### PR TITLE
ci: migrate to go-semantic-release

### PR DESCRIPTION
**Pull request by odsod**
Part of removing build-time dependency on Node.js for Go projects.

### CODE REVIEW

**Review by alethenorio — COMMENTED** [review]
Doesn't that mean we may end bumping this to v2 on breaking changes?

**Review by Edholm — APPROVED** [review]
Noice!

**Review by viktorvoltaire — APPROVED** [review]
This is awesome, `allow-initial-development-versions` “Starts your initial development release at 0.1.0” do we need to have this given our release is still pre 1.0.0? Or will it just continue where we’re at

**Comment by odsod** [comment]
@alethenorio Good point! If we are at 0.x I would assume that it still only increments the minor version, but we should verify that - the documentation of go-semantic-release is not super clear.

@viktorvoltaire Good catch - I'm adding that!

**Pull request merged**
